embed_assets: on

javascripts:
  common:  
    - public/javascripts/plugins.js      
    - public/javascripts/rails.js  
    - public/javascripts/jquery.prettyPhoto.js    
    - public/javascripts/application.js
    - public/javascripts/jquery-ui-1.8.11.custom.min.js
    - public/formalize/javascripts/jquery.formalize.js
  admin:
    - public/javascripts/jquery.dataTables.js
  

stylesheets:
  common:
    - public/stylesheets/screen.css
    - public/stylesheets/prettyPhoto.css
    - public/fonts/fonts.css
    - public/stylesheets/forms.css
    - public/stylesheets/smoothness/jquery-ui-1.8.11.custom.css
    - public/formalize/stylesheets/formalize.css
  admin:
    - public/table/css/demo_table.css
    - public/table/css/demo_table_jui.css