require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe SubtypesController do

  def mock_subtype(stubs={})
    @mock_subtype ||= mock_model(Subtype, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all subtypes as @subtypes" do
      Subtype.stub(:all) { [mock_subtype] }
      get :index
      assigns(:subtypes).should eq([mock_subtype])
    end
  end

  describe "GET show" do
    it "assigns the requested subtype as @subtype" do
      Subtype.stub(:find).with("37") { mock_subtype }
      get :show, :id => "37"
      assigns(:subtype).should be(mock_subtype)
    end
  end

  describe "GET new" do
    it "assigns a new subtype as @subtype" do
      Subtype.stub(:new) { mock_subtype }
      get :new
      assigns(:subtype).should be(mock_subtype)
    end
  end

  describe "GET edit" do
    it "assigns the requested subtype as @subtype" do
      Subtype.stub(:find).with("37") { mock_subtype }
      get :edit, :id => "37"
      assigns(:subtype).should be(mock_subtype)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created subtype as @subtype" do
        Subtype.stub(:new).with({'these' => 'params'}) { mock_subtype(:save => true) }
        post :create, :subtype => {'these' => 'params'}
        assigns(:subtype).should be(mock_subtype)
      end

      it "redirects to the created subtype" do
        Subtype.stub(:new) { mock_subtype(:save => true) }
        post :create, :subtype => {}
        response.should redirect_to(subtype_url(mock_subtype))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved subtype as @subtype" do
        Subtype.stub(:new).with({'these' => 'params'}) { mock_subtype(:save => false) }
        post :create, :subtype => {'these' => 'params'}
        assigns(:subtype).should be(mock_subtype)
      end

      it "re-renders the 'new' template" do
        Subtype.stub(:new) { mock_subtype(:save => false) }
        post :create, :subtype => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested subtype" do
        Subtype.stub(:find).with("37") { mock_subtype }
        mock_subtype.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :subtype => {'these' => 'params'}
      end

      it "assigns the requested subtype as @subtype" do
        Subtype.stub(:find) { mock_subtype(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:subtype).should be(mock_subtype)
      end

      it "redirects to the subtype" do
        Subtype.stub(:find) { mock_subtype(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(subtype_url(mock_subtype))
      end
    end

    describe "with invalid params" do
      it "assigns the subtype as @subtype" do
        Subtype.stub(:find) { mock_subtype(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:subtype).should be(mock_subtype)
      end

      it "re-renders the 'edit' template" do
        Subtype.stub(:find) { mock_subtype(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested subtype" do
      Subtype.stub(:find).with("37") { mock_subtype }
      mock_subtype.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the subtypes list" do
      Subtype.stub(:find) { mock_subtype }
      delete :destroy, :id => "1"
      response.should redirect_to(subtypes_url)
    end
  end

end
